### ISSUE TITLE
HTTP 401 when fetching the library the plugin

### ISSUE THREAD

**Issue by idrissneumann** [pulumiverse/pulumi-ovh#56]
Hi.

This error is very recent, it's happening since today.

Error message:

```shell
downloading from github://api.github.com/lbrlabs: failed to download plugin: ovh-0.2.0: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
```

The pipeline trace:

```shell
#11 76.47       [resource plugin ovh-0.2.0] installing
#11 76.47       warning: Error downloading plugin: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Will retry in 80ms [1/5]
#11 76.47       warning: Error downloading plugin: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Will retry in 160ms [2/5]
#11 76.47       warning: Error downloading plugin: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Will retry in 320ms [3/5]
#11 76.47       warning: Error downloading plugin: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Will retry in 640ms [4/5]
#11 76.47       warning: Error downloading plugin: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Will retry in 1.28s [5/5]
#11 76.47       error: [resource plugin ovh-0.2.0] downloading from github://api.github.com/lbrlabs: failed to download plugin: ovh-0.2.0: 401 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-ovh/releases/tags/v0.2.0
#11 76.47       Traceback (most recent call last):
#11 76.47         File "<string>", line 2, in <module>
#11 76.47         File "<pip-setuptools-caller>", line 34, in <module>
#11 76.47         File "/tmp/pip-install-ostjqdvd/lbrlabs-pulumi-ovh_83153be18d75400a8ce07ad365a10ac9/setup.py", line 40, in <module>
#11 76.47           setup(name='lbrlabs_pulumi_ovh',
#11 76.47         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
#11 76.47           return distutils.core.setup(**attrs)
#11 76.47         File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
#11 76.47           dist.run_commands()
#11 76.47         File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
#11 76.47           self.run_command(cmd)
#11 76.47         File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
#11 76.47           cmd_obj.run()
#11 76.47         File "/tmp/pip-install-ostjqdvd/lbrlabs-pulumi-ovh_83153be18d75400a8ce07ad365a10ac9/setup.py", line 18, in run
#11 76.47           check_call(['pulumi', 'plugin', 'install', 'resource', 'ovh', PLUGIN_VERSION, '--server', 'github://api.github.com/lbrlabs'])
#11 76.47         File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
#11 76.47           raise CalledProcessError(retcode, cmd)
#11 76.47       subprocess.CalledProcessError: Command '['pulumi', 'plugin', 'install', 'resource', 'ovh', '0.2.0', '--server', 'github://api.github.com/lbrlabs']' returned non-zero exit status 255.
#11 76.47       [end of output]
#11 76.47   
#11 76.47   note: This error originates from a subprocess, and is likely not a problem with pip.
#11 76.47 error: legacy-install-failure
#11 76.47 
#11 76.47 × Encountered error while trying to install package.
#11 76.47 ╰─> lbrlabs-pulumi-ovh
```

Step to reproduce the bug:

1. Add `lbrlabs-pulumi-ovh` inside a `requirements.txt` file
2. Add those commandes inside a Dockerfile

```shell
RUN pip install --upgrade pip && \
         pip install --no-cache-dir -r requirements.txt
```

3. Build the container

Thanks for your help.

**Comment by dirien** [comment]
hi @idrissneumann,

FYI: I update the provider to the latest OVH version: 0.29.0!
